# Generated by Django 4.2 on 2023-04-08 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0005_produto_preco'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='em_promocao',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='promocao',
        ),
    ]
